CREATE VIEW VW_CLIENTES AS 
SELECT 
COD_CLI,
RUC_CLI,
RAZSOC_CLI,
DIR_CLI,
UBIGEO.COD_UBI,
CONCAT(DEP_UBI,', ',PRO_UBI,', ',DIS_UBI) AS UBIGEO
FROM CLIENTE
INNER JOIN UBIGEO ON UBIGEO.COD_UBI = CLIENTE.COD_UBI;
GO


CREATE VIEW VW_EMPRESAS AS 
SELECT 
COD_EMP,
RAZSOC_EMP,
RUC_EMP,
DIR_EMP,
UBIGEO.COD_UBI,
CONCAT(DEP_UBI,', ',PRO_UBI,', ',DIS_UBI) AS UBIGEO
FROM EMPRESA
INNER JOIN UBIGEO ON UBIGEO.COD_UBI = EMPRESA.COD_UBI
GO